#ifndef POMODORO_TIMER_EVENTS_H
#define POMODORO_TIMER_EVENTS_H
enum PomodoroTimerEvent {
  NONE,
  WORK_PERIOD_STARTED,
  WORK_PERIOD_ENDED,
  WORK_PERIOD_ABORTED,
  REST_PERIOD_ENDED,
  REST_PERIOD_ABORTED
};
#endif
